import Footer from "@/components/Layouts/Footer";
import Navbar from "@/components/Layouts/Navbar";
import Head from "next/head";

export default function Main({ children, className, title = "Light Lines - Your beacon of inspiration" }) {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main className={className}>{children}</main>
            <Footer />
        </>
    );
}
